### ISSUE TITLE
Fix trailer full screen.

### ISSUE THREAD

**Issue by Japoilski** [TorrentLookup/Flixtor#10]

**Comment by Japoilski** [comment]
I still not have found a solution for the embed Youtube full screen.

Node-webkit problem. 
https://github.com/rogerwang/node-webkit/issues/55

Anyone has a solution?

**Comment by gtuk** [comment]
Not a solution but maybe an workaround.
1. Add the node-youtube-dl node module to your project
2. Get  direct youtube video url
3. Create your own video tag with direct url as src
4. Found this on github! Bind an click on the full screen button. Then for example switch to an other fullscreen frame.

// video tag with specific id
$('#video_trailer').bind('click', function(e) {
var hit = false;

var x = e.pageX - this.offsetLeft;
var y = e.pageY - this.offsetTop;
var w = this.offsetWidth;
var h = this.offsetHeight;

if (w < 800) {
hit = (y > h - 35) && (x > w - 45);
} else {
var xmin = w / 2 + 355;
var xmax = w / 2 + 390;
hit = (y > h - 35) && (x > xmin && x < xmax);
}

if (hit) {
// for example switch to new trailerFullscreen frame
setTimeout(function () {window.location = "trailerFullscreen.html"; }, 2000);
e.preventDefault();
}
});

I test this an its working with the current master
