### ISSUE TITLE
Fix subtitle encoding problems.

### ISSUE THREAD

**Issue by Japoilski** [TorrentLookup/Flixtor#11]
Example reported by users
- When á, ã, or, ô appears, it show just a "?" icon

**Comment by ghost** [comment]
Can you include fix on characters; > ć č š đ ž < for Estern Europe; Srbia(Srbija) , Croatia (Hrvaška/Hrvatska) , Slovenia (Slovenija) and others? Please... We have the same issue when comes to these characters, it always show this  --> ? <--- character instead one of the letter i writte about ...

**Comment by ricardofunke** [comment]
Version 1.5 still has encoding problems with subtitles. Brazilian and Portuguese doesn't shows the correct characters for accentuations.

I'm using Arch Linux
Kernel version: 3.14.1-1-ARCH x86_64

[root@funkenote opt]# locale
LANG=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=

The image shows an example where it should be "O que você sabe sobre a República Tcheca?"

![captura de tela de 2014-04-25 21 11 11](https://cloud.githubusercontent.com/assets/670161/2806935/6ca16d0a-ccd7-11e3-8a45-5cef7ea1a4a7.png)

**Comment by Japoilski** [comment]
Fixed #37 :p

**Comment by ricardofunke** [comment]
Ok thanks, would be available on 1.6 release? Would it take long to be ready?
