### ISSUE TITLE
Couldn't load plug-in.

### ISSUE THREAD

**Issue by Tranberry** [TorrentLookup/Flixtor#2]
Just tried to clone and npm-install dl node-webkit and run. Seems to run fine in win7 (64) but can't load any video it just says:

Couldn't load plug-in.

**Comment by Abradolf-Lincler** [comment]
I encounter the same problem when trying to play a xvid format on Ubuntu (13.10) 32bit

**Comment by Japoilski** [comment]
If you want to be able to play the video with the default player instead of vlc you must replace 'ffmpegsumo' of node-webkit by one inside the librairies folder of the project.

If the default player throw an error it will change frame and execute the vlc player. Also, if you don't have the latest vlc media player installed on your computer it will show 'Couldn't load plug-in'.

**Comment by CokYasak** [comment]
Same trouble 'Couldn't load plug-in'  I have the latest VLC.  OX 10.8.3
Worked fine with the movie 'Frozen' but gave me the error with 'Game of Thrones'.

**Comment by 514d3** [comment]
I've got the same issue on Ubuntu GNOME 13.10 32bit; Frozen plays but all other movies and shows return the 'Couldn't load plugin' error.

One question, I'm new to linux so I'm not sure how to "replace 'ffmpegsumo' of node-webkit"; how do you do that?

**Comment by sergiopvilar** [comment]
Same issue on Mac OSX Mavericks. I've installed Perian and I have the latest VLC version.

**Comment by Japoilski** [comment]
Make sure when you install VLC to check web plugins in the list.
![vlc](https://cloud.githubusercontent.com/assets/7190299/2735739/f60088b2-c663-11e3-97f3-77eb45c4e285.png)

**Comment by sergiopvilar** [comment]
How to do this on a mac?

**Comment by Japoilski** [comment]
Web plugin is not available for mac.

**These plugins will not run on 10.6 or later.
http://www.videolan.org/vlc/download-macosx.html

We need to wait.

**Comment by Japoilski** [comment]
MAC user only.
If you want to resolve the 'could not load plugin' install this version of VLC
http://nightlies.videolan.org/build/macosx-intel/VLC-webplugin-20140425-0555.dmg
Thanks to Felix Paul Kühne from twitter for pointing that out. https://twitter.com/feepk

How to:
Mount the .dmg image and drag the plugin to the "internet plugins" alias icon and it will copy it to the correct folder.

**Comment by Garito** [comment]
Japoliski's solution works with the video but then subtitles are lost (the vlc webplugin changes the ui so can't select any subtitle)

**Comment by Japoilski** [comment]
Good point.
I made another issue on that matter. #48

**Comment by Garito** [comment]
Thanks and sorry for not make it by myself... (the new issue)

**Comment by Japoilski** [comment]
No worries ;)
