### ISSUE TITLE
Keyboard player shortcuts

### ISSUE THREAD

**Issue by Japoilski** [TorrentLookup/Flixtor#25]
| Key | Action |
| --- | :-: |
| space | play/pause |
| f | toggle full screen |
| m | mute |
| esc | remove full screen |
| backspace | reload player |

**Comment by t0mf00lery** [comment]
With these commands it's not immediately obvious how to leave a playing video. Normally the 'x' in the top corner would indicate quitting the app entirely. It's a little confusing to use this button to return to the main menu as well. 

Perhaps mapping 'esc' to close the video player would be less confusing. An onscreen option would be the most straight forward though.
