### ISSUE TITLE
character error

### ISSUE THREAD

**Issue by arnaud512** [TorrentLookup/Flixtor#26]
Hi, i'm french and in movie, the accented character are not visible. 
it should be é,è, and à
![2014-04-14_15-26-30](https://cloud.githubusercontent.com/assets/3939593/2695685/99eb3bf8-c3d9-11e3-81b6-45f44b38e4d0.png)

Voila,

Thank's for fix it :)

ps: i'm on mac os x 10.9

**Comment by gianpaj** [comment]
Duplicates #11

**Comment by ghost** [comment]
This could be fixed by adding <code>charset='UTF-8'</code> at line 65 of file <code>player.html</code> file.

https://github.com/TorrentLookup/Flixtor/blob/master/frames/player.html

The build app crashes in Linux so I can't test this.

**Comment by Japoilski** [comment]
<code>charset='UTF-8'</code>  is already the default. Also, I added the line into the <code>player.html</code> but it does not fix the issue. 

I found that sometimes you are able to view special characters  and sometimes you can't. We use opensubtitles.org and I think that people uploading .srt files are not always saving them as UTF-8. 

We might need to download the subtitle then save it with UTF-8 encoding and use the new file with the proper encoding for the player.

**Comment by shali1995** [comment]
so how can I fix the Hebrew sub problem?
@Japoilski

**Comment by Japoilski** [comment]
I will try to fix this tomorrow. If I succeed I will publish beta 1.5 :smile:

**Comment by shali1995** [comment]
thank you! @Japoilski

**Comment by ghost** [comment]
Can you include fix on characters; > ć č š đ ž < for Estern Europe; Srbia(Srbija) , Croatia (Hrvaška/Hrvatska) , Slovenia (Slovenija) and others? Please... We have the same issue when comes to these characters, it always show this  --> ? <--- character instead one of the letter i writte about ...

**Comment by Japoilski** [comment]
:angry: I tried to fix it but without success.
I need more time...

**Comment by ghost** [comment]
Thank you for trying,...
I hope you get it done at some point and push extra update if we missed this update. I realy hope for this to be solved. You guys build Flixtor in metter of days/weeks so i have high hopes for you to find some solution for this one.  :)

**Comment by Japoilski** [comment]
Good news guys! I found a solution and I will make the implementation ASAP.
@TurnerOS Feel free to take my solution for PT when I commit my work.

**Comment by ghost** [comment]
Japoilski@ 
I'm glad to hear you find solution for Flixtor so characters will be showen the right way in next relese. :) 

---

As far as i know Popcorn Time already find solution for all languages and flags weeks ago (solved by one user for all language and flags) It will be in next relese. Anyway thanks for your offer and i look forward to see next Flixtor relese...  :)
