### ISSUE TITLE
Audio not playing (Mac OS X 10.9.2)

### ISSUE THREAD

**Issue by JayS90** [TorrentLookup/Flixtor#3]
Running Mac OS X 10.9.2 and Flixtor beta 1.4. I press play on a heavily seeded file, loads/buffers, plays the video file and everything is fine apart from no audio.

Hardware working properly, double and triple checked. Restarted my laptop many times too.

I have VLC installed, in case anyone thought it may be a codec issue?

edit: perhaps it's a codec issue after all, as I'm able to get audio from .mp4 files. But tbh I have absolutely no idea >.<

**Comment by gianpaj** [comment]
Same here. Works on `.mp4` files but not on `.mkv`
For example in Series search for:

```
Torrent Name: Game.of.Thrones.S04E01.720p.HDTV.x264-KILLERS.mkv
Added date: 4/6/2014 11:20:59 PM
```

But peerflix does actually work:
`peerflix magnet:?xt=urn:btih:f1020fb01a39b49cea2f0d78c7b29182a4440660 --vlc`

**Comment by Japoilski** [comment]
We should run vlc instead of the default player when the file is .mkv or maybe we can offer the user to switch players.

**Comment by JayS90** [comment]
Does anyone know if it's possible to (or how to) use VLC to play the stream from Flixtor? I wouldn't have the first idea of where to start, but I'm guessing VLC would need to connect to it as a network stream?

edit: just Googled how to using peerflix, seems like a bit of an arduous process for me. Unless there's another way to do it that someone else wants to share? :)

I'm also experiencing another bug, which I think most users are, where if you pause the video you're watching and then resume it after a few seconds the 'couldn't load plug-in' message appears. Hit backspace, and the video starts from the beginning.

**Comment by mhmdmodan** [comment]
Having this problem too. A work around is to pause the player for several minutes then play. The player will have lost internet connection, then default to VLC and start from the beginning. Audio will play in VLC. Only issue I have with that is VLC has a terrible contrast ratio.

I'd suggest also adding an option for us to choose the player (VLC or windows media player) as Flixtor's can be a bit jerky.

**Comment by Japoilski** [comment]
Switch to VLC when you don't have any sound.
