### ISSUE TITLE
Character Error on beta 1.5

### ISSUE THREAD

**Issue by tiagoplacido** [TorrentLookup/Flixtor#37]
The character error still exits on pt-pt, pt-br subtitles.
http://imgur.com/AguaZhj
http://imgur.com/LFsNt4k

apart from this the app works great
Thanks

**Comment by Japoilski** [comment]
Really! Fa&# my life.

**Comment by ghost** [comment]
Yes, sadley some characters (not all) are still looking ''strange'' when comes to my region. :)

---

But i know you get it right in time...
Keep it up with good work...

**Comment by Japoilski** [comment]
pt-pt
![image](https://cloud.githubusercontent.com/assets/7190299/2797703/1e551bea-cc39-11e3-8c54-eebd671f7cf5.png)

Does that seems right?

**Comment by Japoilski** [comment]
Muahahah I think I have it now

pt-br
![image](https://cloud.githubusercontent.com/assets/7190299/2797766/a1e6fb84-cc3b-11e3-8d52-0d9b87a6e793.png)

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
I hope it would work for EsternEU too, at least for 90% of this special characters.. :)

**Comment by Yoshimit** [comment]
Unfortunately, this error still occurs in Flixtor 1.0.
Maybe this can help ?
https://www.npmjs.org/package/jschardet
