### ISSUE TITLE
Subtitle size can't be changed.

### ISSUE THREAD

**Issue by RamiO** [TorrentLookup/Flixtor#4]
Subtitle size can't be changed....  original popcorn time and "Cuevana Storm" have possibility to change subtitle size (that ability is most needed for anyone who uses subtitles). Now the size is just too tiny for most situations (except when watching from computer screen when the distance is not much).

**Comment by Garito** [comment]
+1

**Comment by ricardofunke** [comment]
+1 Can't use it in my TV

**Comment by ricardofunke** [comment]
Actually, it's hard to read even in my laptop... :(

**Comment by baggott** [comment]
You can change subtitles size and color.
Open the flie: \path_to_flixtor\styles\video-skin.css
look to the Attribute: .video-js .vjs-subtitles
I change color to yellow and add font-size: 3em;

But Flixtor team will be this in next beta release.

**Comment by Garito** [comment]
Fuck, man... I've made the modification but I can't test it because, at least right now, can't find any film who flixtor load with subtitles
Will try later but this is super annoying: the program sometimes don't load any film, then it loads but fuckingplug-in problem, other times it loads but without subtitles (even films I've already seen with flixtor in bad coded spanish)
Super, super unstable and annoying

**Comment by Japoilski** [comment]
OpenSubtitles.com was down. I think they are now back online now :) Also, we are here to make Flixtor better it will be less and less unstable in the future.

**Comment by baggott** [comment]
great!

## 

Alexandre Baggott Ayres
alexandrebayres@gmail.com
f: (11) 9 8205.9607 / (67) 9862.1889
skype: alexandrebayres

**Comment by Garito** [comment]
Sorry for my frustration... don't wanna pay it with no one
Let me share the best realisation I've made this last times: FEEDBACK
Awareness is to realize something: you become aware of something by understanding how it works by learning how the FEEDBACK apears
In this particular case: the more info the users has the better can use the torrent thing

**Comment by Garito** [comment]
BTW the tip about the class for the subtitles works

**Comment by baggott** [comment]
Thanks
