### ISSUE TITLE
Search / Stream by magnet link

### ISSUE THREAD

**Issue by gianpaj** [TorrentLookup/Flixtor#5]

**Comment by vlasvlasvlas** [comment]
+1 really necesary

**Comment by gtuk** [comment]
Fixed in my fork and did a pull request https://github.com/TorrentLookup/Flixtor/pull/42

**Comment by mhmdmodan** [comment]
Sorry for my ignorance, but is this feature currently implemented, gtuk? I tried it and I get an error: Object [object Object] has no method 'showMsg'

**Comment by gtuk** [comment]
No they don't merged it into the current master. I fixed it in my fork https://github.com/gtuk/Flixtor-1. 
I will send an pull request, to TorrentLookup. Meanwhile you can use my fork or wait until they merge it
