### ISSUE TITLE
Choose a player

### ISSUE THREAD

**Issue by mhmdmodan** [TorrentLookup/Flixtor#51]
Option to choose a player before streaming and switch the default player. Flixtor's player seems to hiccup a bit, and VLC is washed out.

**Comment by Japoilski** [comment]
Already done but not released. Here is an example

![image](https://cloud.githubusercontent.com/assets/7190299/2837911/c956e500-d026-11e3-8920-06d83c271672.png)

**Comment by ghost** [comment]
@Japoilski 

---

i thought you say ''this weekend''.. well, i gues i have to wait.. :(

---

**Comment by Japoilski** [comment]
I have time to work on it tomorrow and I think I might be able to release it if I have no major issues.
I'll do my best :smile:

**Comment by ghost** [comment]
OK. i'll wait..  :)
