### ISSUE TITLE
Charset problems on 1.0 again

### ISSUE THREAD

**Issue by Yoshimit** [TorrentLookup/Flixtor#53]
Hi there.
#37 is not fixed, unfortunately.

Maybe this could help:
https://www.npmjs.org/package/jschardet

**Comment by Japoilski** [comment]
What language & can you submit an image?

**Comment by ghost** [comment]
Maybe this will help:
https://www.npmjs.org/package/jschardet

---

Could you look at ''European'' special charachters also for these countrys, please; 
- Slovenia+n  (Slovenija,Slovenia)
- Craoatia+n (Hrvaška), 
- Srbia+n (Srbija), 
- Bosnia+n (Bosna)

special charachters (Big>> Č, Ć, Ž, Š, Đ /Small>> č, ć, ž, š, đ )

**Comment by Yoshimit** [comment]
Japoilski,
Language: pt-br
Example: Hannibal s01e06/07

I'll upload a image later tonight.
Thank you.

**Comment by Yoshimit** [comment]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/7319095/2885580/43ac8d88-d4c7-11e3-9795-914a5e1341b9.png)

It should be:
"Jack, é a Miriam. Não quero morrer assim."

Thank you.
