### ISSUE TITLE
Flixtor - 1.0.1

### ISSUE THREAD

**Issue by Japoilski** [TorrentLookup/Flixtor#55]
Hot fix!
Fix minor issues.

**Comment by ghost** [comment]
Is there auto hot fix with auto update or we must manual download from Flixtors website to get 1.0.1 ?
On website latest app downaod is 1.0.0. . that's why i ask..

**Comment by Japoilski** [comment]
I will add auto-update in this version. It's gonna be really easy to publish and less annoying for the users.

**Comment by Japoilski** [comment]
Oops that was suppose to be a milestone.

**Comment by ghost** [comment]
Now i get it what you mean .. 
I get it all wrong first time..  :)
